### PR TITLE
Additional Features

### PR DESCRIPTION
**Pull request by peppelinux**
All the Additional issues in the master project have been developed.
Regarding your last review:

- Data consent is now a template
- PersistentID and most popular nameID formats are developed
- less improvements

After this latest commits I'll produce a separate project so, take what you want from this and thank you all.

I'll do the same PR to the master project.
Bye

### CODE REVIEW

**Comment by askvortsov1** [comment]
Hi, thanks a lot for this! I've cherry-picked commits not related to the confirmation page. It's been great collaborating with you on this!

**Comment by peppelinux** [comment]
I suggest you to take a look to
https://github.com/UniversitaDellaCalabria/uniAuth

It takes the fly ... It also have the 81% of code coverage

**Comment by askvortsov1** [comment]
Hey, thanks for sharing that, it looks great! One thing though: this looks like a standalone system, as opposed to a django installable app. Are there any plans to move the actual uniauth component out to a pip installable repo?

**Comment by peppelinux** [comment]
We can do that without any constraits, sure. Let's start talking about It on uniAuth repo and Remember to put a star on it 😉

**Pull request closed without merging**
